services:
  turdbot:
    image: "ionburger/turdbot:latest"
    restart: always
    container_name: turdbot
    depends_on:
      - mongodb
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=mongodb
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
